#!/bin/sh
echo Compiling...
./build.sh

echo Copying temporary files...
cp -R ../res jar/ 

echo Creating archive...
jar cmf makejar.mf ../lib/csheets.jar -C jar csheets

echo Removing temporary files...
rm -R jar
